apiVersion: v1
kind: Service
metadata:
  name: devopstask-flask-service
spec:
  type: NodePort
  selector:
    app: devopstask-flask
  ports:
    - port: 5002
      targetPort: 5002
      nodePort: 30082